name: PDF Generation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt || true

      - name: Run PDF generation script
        run: |
          python src/sample_script.py

      - name: Upload generated PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: docs/*.pdf
          name: Generate PDF & (optionally) redeploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "src/requirements.txt" ]; then pip install -r src/requirements.txt; fi

      - name: Run PDF generation
        run: |
          python src/sample_script.py

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: docs/*.pdf

      # Optional: commit docs/*.pdf back to the repo to trigger Koyeb auto-deploy.
      # WARNING: This will push to your repo; ensure branch protection rules allow
      # this flow (or use a separate deploy branch).
      - name: Commit generated PDFs (optional)
        if: ${{ always() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.pdf || true
          git commit -m "ci: add generated pdf [skip ci]" || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
