name: PDF Generation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt || true

      - name: Run PDF generation script
        run: |
          python src/sample_script.py

      - name: Upload generated PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: docs/*.pdf
          
