from pathlib import Path

def generate_pdf(output_path="docs/sample.pdf"):
    Path("docs").mkdir(exist_ok=True)
    # Placeholder PDF content
    with open(output_path, "w") as f:
        f.write("This is a sample PDF placeholder.")
    print(f"PDF generated at {output_path}")

if __name__ == "__main__":
    import sys
    deploy = "--deploy" in sys.argv
    if deploy:
        print("Deploy step triggered (placeholder)")
    else:
        generate_pdf()
        
